// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/allora-network/allora-sdk-go/gen/interfaces"
	"github.com/allora-network/allora-sdk-go/txsend"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTxBroadcaster creates a new instance of MockTxBroadcaster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxBroadcaster(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxBroadcaster {
	mock := &MockTxBroadcaster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxBroadcaster is an autogenerated mock type for the TxBroadcaster type
type MockTxBroadcaster struct {
	mock.Mock
}

type MockTxBroadcaster_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxBroadcaster) EXPECT() *MockTxBroadcaster_Expecter {
	return &MockTxBroadcaster_Expecter{mock: &_m.Mock}
}

// AccountInfo provides a mock function for the type MockTxBroadcaster
func (_mock *MockTxBroadcaster) AccountInfo(ctx context.Context, address string) (uint64, uint64, error) {
	ret := _mock.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for AccountInfo")
	}

	var r0 uint64
	var r1 uint64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uint64, uint64, error)); ok {
		return returnFunc(ctx, address)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uint64); ok {
		r0 = returnFunc(ctx, address)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) uint64); ok {
		r1 = returnFunc(ctx, address)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, address)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTxBroadcaster_AccountInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccountInfo'
type MockTxBroadcaster_AccountInfo_Call struct {
	*mock.Call
}

// AccountInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
func (_e *MockTxBroadcaster_Expecter) AccountInfo(ctx any, address any) *MockTxBroadcaster_AccountInfo_Call {
	return &MockTxBroadcaster_AccountInfo_Call{Call: _e.mock.On("AccountInfo", ctx, address)}
}

func (_c *MockTxBroadcaster_AccountInfo_Call) Run(run func(ctx context.Context, address string)) *MockTxBroadcaster_AccountInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxBroadcaster_AccountInfo_Call) Return(accountNumber uint64, sequence uint64, err error) *MockTxBroadcaster_AccountInfo_Call {
	_c.Call.Return(accountNumber, sequence, err)
	return _c
}

func (_c *MockTxBroadcaster_AccountInfo_Call) RunAndReturn(run func(ctx context.Context, address string) (uint64, uint64, error)) *MockTxBroadcaster_AccountInfo_Call {
	_c.Call.Return(run)
	return _c
}

// Broadcast provides a mock function for the type MockTxBroadcaster
func (_mock *MockTxBroadcaster) Broadcast(ctx context.Context, signedTx []byte, mode txsend.BroadcastMode) (*txsend.BroadcastResult, error) {
	ret := _mock.Called(ctx, signedTx, mode)

	if len(ret) == 0 {
		panic("no return value specified for Broadcast")
	}

	var r0 *txsend.BroadcastResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, txsend.BroadcastMode) (*txsend.BroadcastResult, error)); ok {
		return returnFunc(ctx, signedTx, mode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, txsend.BroadcastMode) *txsend.BroadcastResult); ok {
		r0 = returnFunc(ctx, signedTx, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*txsend.BroadcastResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, txsend.BroadcastMode) error); ok {
		r1 = returnFunc(ctx, signedTx, mode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxBroadcaster_Broadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Broadcast'
type MockTxBroadcaster_Broadcast_Call struct {
	*mock.Call
}

// Broadcast is a helper method to define mock.On call
//   - ctx context.Context
//   - signedTx []byte
//   - mode txsend.BroadcastMode
func (_e *MockTxBroadcaster_Expecter) Broadcast(ctx any, signedTx any, mode any) *MockTxBroadcaster_Broadcast_Call {
	return &MockTxBroadcaster_Broadcast_Call{Call: _e.mock.On("Broadcast", ctx, signedTx, mode)}
}

func (_c *MockTxBroadcaster_Broadcast_Call) Run(run func(ctx context.Context, signedTx []byte, mode txsend.BroadcastMode)) *MockTxBroadcaster_Broadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 txsend.BroadcastMode
		if args[2] != nil {
			arg2 = args[2].(txsend.BroadcastMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTxBroadcaster_Broadcast_Call) Return(broadcastResult *txsend.BroadcastResult, err error) *MockTxBroadcaster_Broadcast_Call {
	_c.Call.Return(broadcastResult, err)
	return _c
}

func (_c *MockTxBroadcaster_Broadcast_Call) RunAndReturn(run func(ctx context.Context, signedTx []byte, mode txsend.BroadcastMode) (*txsend.BroadcastResult, error)) *MockTxBroadcaster_Broadcast_Call {
	_c.Call.Return(run)
	return _c
}

// EstimateGas provides a mock function for the type MockTxBroadcaster
func (_mock *MockTxBroadcaster) EstimateGas(ctx context.Context, unsignedTx []byte) (uint64, error) {
	ret := _mock.Called(ctx, unsignedTx)

	if len(ret) == 0 {
		panic("no return value specified for EstimateGas")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (uint64, error)); ok {
		return returnFunc(ctx, unsignedTx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) uint64); ok {
		r0 = returnFunc(ctx, unsignedTx)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, unsignedTx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxBroadcaster_EstimateGas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EstimateGas'
type MockTxBroadcaster_EstimateGas_Call struct {
	*mock.Call
}

// EstimateGas is a helper method to define mock.On call
//   - ctx context.Context
//   - unsignedTx []byte
func (_e *MockTxBroadcaster_Expecter) EstimateGas(ctx any, unsignedTx any) *MockTxBroadcaster_EstimateGas_Call {
	return &MockTxBroadcaster_EstimateGas_Call{Call: _e.mock.On("EstimateGas", ctx, unsignedTx)}
}

func (_c *MockTxBroadcaster_EstimateGas_Call) Run(run func(ctx context.Context, unsignedTx []byte)) *MockTxBroadcaster_EstimateGas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxBroadcaster_EstimateGas_Call) Return(gas uint64, err error) *MockTxBroadcaster_EstimateGas_Call {
	_c.Call.Return(gas, err)
	return _c
}

func (_c *MockTxBroadcaster_EstimateGas_Call) RunAndReturn(run func(ctx context.Context, unsignedTx []byte) (uint64, error)) *MockTxBroadcaster_EstimateGas_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForTx provides a mock function for the type MockTxBroadcaster
func (_mock *MockTxBroadcaster) WaitForTx(ctx context.Context, txHash string) (*txsend.TxResult, error) {
	ret := _mock.Called(ctx, txHash)

	if len(ret) == 0 {
		panic("no return value specified for WaitForTx")
	}

	var r0 *txsend.TxResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*txsend.TxResult, error)); ok {
		return returnFunc(ctx, txHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *txsend.TxResult); ok {
		r0 = returnFunc(ctx, txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*txsend.TxResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, txHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxBroadcaster_WaitForTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForTx'
type MockTxBroadcaster_WaitForTx_Call struct {
	*mock.Call
}

// WaitForTx is a helper method to define mock.On call
//   - ctx context.Context
//   - txHash string
func (_e *MockTxBroadcaster_Expecter) WaitForTx(ctx any, txHash any) *MockTxBroadcaster_WaitForTx_Call {
	return &MockTxBroadcaster_WaitForTx_Call{Call: _e.mock.On("WaitForTx", ctx, txHash)}
}

func (_c *MockTxBroadcaster_WaitForTx_Call) Run(run func(ctx context.Context, txHash string)) *MockTxBroadcaster_WaitForTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxBroadcaster_WaitForTx_Call) Return(txResult *txsend.TxResult, err error) *MockTxBroadcaster_WaitForTx_Call {
	_c.Call.Return(txResult, err)
	return _c
}

func (_c *MockTxBroadcaster_WaitForTx_Call) RunAndReturn(run func(ctx context.Context, txHash string) (*txsend.TxResult, error)) *MockTxBroadcaster_WaitForTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCosmosTxPool creates a new instance of MockCosmosTxPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCosmosTxPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCosmosTxPool {
	mock := &MockCosmosTxPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCosmosTxPool is an autogenerated mock type for the CosmosTxPool type
type MockCosmosTxPool struct {
	mock.Mock
}

type MockCosmosTxPool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCosmosTxPool) EXPECT() *MockCosmosTxPool_Expecter {
	return &MockCosmosTxPool_Expecter{mock: &_m.Mock}
}

// Auth provides a mock function for the type MockCosmosTxPool
func (_mock *MockCosmosTxPool) Auth() interfaces.AuthClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Auth")
	}

	var r0 interfaces.AuthClient
	if returnFunc, ok := ret.Get(0).(func() interfaces.AuthClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.AuthClient)
		}
	}
	return r0
}

// MockCosmosTxPool_Auth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Auth'
type MockCosmosTxPool_Auth_Call struct {
	*mock.Call
}

// Auth is a helper method to define mock.On call
func (_e *MockCosmosTxPool_Expecter) Auth() *MockCosmosTxPool_Auth_Call {
	return &MockCosmosTxPool_Auth_Call{Call: _e.mock.On("Auth")}
}

func (_c *MockCosmosTxPool_Auth_Call) Run(run func()) *MockCosmosTxPool_Auth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCosmosTxPool_Auth_Call) Return(authClient interfaces.AuthClient) *MockCosmosTxPool_Auth_Call {
	_c.Call.Return(authClient)
	return _c
}

func (_c *MockCosmosTxPool_Auth_Call) RunAndReturn(run func() interfaces.AuthClient) *MockCosmosTxPool_Auth_Call {
	_c.Call.Return(run)
	return _c
}

// Tx provides a mock function for the type MockCosmosTxPool
func (_mock *MockCosmosTxPool) Tx() interfaces.TxClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tx")
	}

	var r0 interfaces.TxClient
	if returnFunc, ok := ret.Get(0).(func() interfaces.TxClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.TxClient)
		}
	}
	return r0
}

// MockCosmosTxPool_Tx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tx'
type MockCosmosTxPool_Tx_Call struct {
	*mock.Call
}

// Tx is a helper method to define mock.On call
func (_e *MockCosmosTxPool_Expecter) Tx() *MockCosmosTxPool_Tx_Call {
	return &MockCosmosTxPool_Tx_Call{Call: _e.mock.On("Tx")}
}

func (_c *MockCosmosTxPool_Tx_Call) Run(run func()) *MockCosmosTxPool_Tx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCosmosTxPool_Tx_Call) Return(txClient interfaces.TxClient) *MockCosmosTxPool_Tx_Call {
	_c.Call.Return(txClient)
	return _c
}

func (_c *MockCosmosTxPool_Tx_Call) RunAndReturn(run func() interfaces.TxClient) *MockCosmosTxPool_Tx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClock creates a new instance of MockClock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClock {
	mock := &MockClock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClock is an autogenerated mock type for the Clock type
type MockClock struct {
	mock.Mock
}

type MockClock_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClock) EXPECT() *MockClock_Expecter {
	return &MockClock_Expecter{mock: &_m.Mock}
}

// After provides a mock function for the type MockClock
func (_mock *MockClock) After(d time.Duration) <-chan time.Time {
	ret := _mock.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for After")
	}

	var r0 <-chan time.Time
	if returnFunc, ok := ret.Get(0).(func(time.Duration) <-chan time.Time); ok {
		r0 = returnFunc(d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan time.Time)
		}
	}
	return r0
}

// MockClock_After_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'After'
type MockClock_After_Call struct {
	*mock.Call
}

// After is a helper method to define mock.On call
//   - d time.Duration
func (_e *MockClock_Expecter) After(d any) *MockClock_After_Call {
	return &MockClock_After_Call{Call: _e.mock.On("After", d)}
}

func (_c *MockClock_After_Call) Run(run func(d time.Duration)) *MockClock_After_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClock_After_Call) Return(timeCh <-chan time.Time) *MockClock_After_Call {
	_c.Call.Return(timeCh)
	return _c
}

func (_c *MockClock_After_Call) RunAndReturn(run func(d time.Duration) <-chan time.Time) *MockClock_After_Call {
	_c.Call.Return(run)
	return _c
}

// Now provides a mock function for the type MockClock
func (_mock *MockClock) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockClock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockClock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockClock_Expecter) Now() *MockClock_Now_Call {
	return &MockClock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *MockClock_Now_Call) Run(run func()) *MockClock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClock_Now_Call) Return(time1 time.Time) *MockClock_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockClock_Now_Call) RunAndReturn(run func() time.Time) *MockClock_Now_Call {
	_c.Call.Return(run)
	return _c
}
